version: '3'
services:
  documentation_build:
    build:
      context: './'
    #command: tail -f /dev/null
    environment:
      - LANGUAGE=${LANGUAGE}
    volumes:
      - ./tex/${LANGUAGE}:/source/${LANGUAGE}
      - ./tex/common:/source/common
      #- ../doc/logs/${LANGUAGE}:/miktex/.miktex/texmfs/data/miktex/log
      - ../doc/${LANGUAGE}:/interface/output
    container_name: learn_with_tello_build_doc