include(${CMAKE_SOURCE_DIR}/../../cmake/functions.cmake)

dynamic_lib_file_ending(DYNAMIC_LIB_FILE_ENDING)

# Remove current libs
set(LIB_LOCATION ${CMAKE_BINARY_DIR}/libs)
file(REMOVE_RECURSE ${LIB_LOCATION})
file(MAKE_DIRECTORY ${LIB_LOCATION})

file(GLOB_RECURSE LIBRARY_FILES ${CMAKE_BINARY_DIR}/../app_modules/*.${DYNAMIC_LIB_FILE_ENDING})
file(COPY ${LIBRARY_FILES} DESTINATION ${LIB_LOCATION})